# Configure parameter values for development time. These will be overriden at runtime with the user provided data
DEBUG_MODE: "T"
NaaS_IP: 'http://10.72.8.21:9091/naas' # 'https://naas.chime-prod.gcp.de.pri.o2.com/naas' # 'http://10.72.8.21:9091/naas'
XPaaS_IP: 'http://10.72.8.78:9092/xpaas' # 'https://xpaas.chime-prod.gcp.de.pri.o2.com/xpaas' # 'http://10.72.8.78:9092/xpaas'
PGW_IP: 'http://10.72.8.78:9093/pgw' # 'https://pgw.chime-prod.gcp.de.pri.o2.com/pgw' # 'http://10.72.8.78:9093/pgw'
Auth_IP: '' # 'https://am.chime-prod.gcp.de.pri.o2.com/gateway/chime/oauth/token'
CLIENT_ID: 'SZc5nxWR2HNT3zL6xr8xIn7S1bQ'
CLIENT_SECRET: 'ChXh2d1AvLqYDfcQopBRFq72D1k'
NAAS_CLUSTER: "NO_P3_M8_1" # "N4G_ULI_MNG_CLUSTER1"
PROVISION_MODE: "OPERATIONAL"
BACKLOG_DURATION: "72h"
BATCH_SIZE: 500
MIN_REQ_SR_THRESHOLD: 90
MIN_REQ_ATTEMPT_THRESHOLD: 100
ACTION_LIMIT: -1